Add a CONTRIBUTING.md so folks know how to engage with this initiative
ossf/DevRel-community pull request #37
Opened 2024-02-09 19:27 UTC by webchick

Here is some information that was shared in Slack, captured here for posterity, to help newcomers to the project hit the ground running.

Credit also to @kdruckman who helped answer open questions!

Note: This document uses a pretty informal tone, and if need be I can "tone" it down 🥁  to read more like the rest of the documentation for OpenSSF. However, given this is a community-facing initiative, I thought it might be good to show some "personality" here, since we can be both a fun group to work with and **also** get Very Important Business™ done. :)

2024-02-09 20:40 UTC, funnelfiasco commented
As someone who just discovered this community and is looking to get started, this is a great v1. :ship:

2024-02-09 21:43 UTC, Cheukting commented
@webchick this is awesome! I think the tone is landing at the sweet spot and I love it! I have added some small reviews otherwise we can merge!

2024-02-11 01:16 UTC, webchick commented
Yay, thanks! 😄 Also I'm not sure if it's the jet lag talking, but I don't seem to see your review comments?

2024-02-12 09:43 UTC, Cheukting requested changes

2024-02-12 09:44 UTC, Cheukting commented
> Yay, thanks! 😄 Also I'm not sure if it's the jet lag talking, but I don't seem to see your review comments?

@webchick my bad, I forgot to actually submit these reviews so there where pending and hidden >_<

2024-02-12 18:46 UTC, webchick commented on CONTRIBUTING.md
> +* **Weekly Office Hours** which are weekly at 20:30 UTC ([your timezone](https://time.is/2030_in_UTC)) These are generally working sessions, but we hope to expand to activities like reviewing CFP sub
D'oh. I apparently got Eastern (what's shown on the [calendar](https://openssf.org/getinvolved/)) and my time zone confused. 🙈

2024-02-12 18:49 UTC, webchick commented on CONTRIBUTING.md
> +If you're new to OpenSSF, you can watch or attend a [Town Hall](https://www.youtube.com/playlist?list=PLVl2hFL_zAh_rQ4oTpM7OKkEm_Y2OWsK8) to get acquainted, as well as join in to any of the other mee
OH, rad! I've never seen that before! +1

2024-02-12 18:54 UTC, webchick commented
OK, I believe this is now done; back to you! :D

2024-02-12 20:27 UTC, Cheukting approved these changes
Awesome!!!!!

2024-02-12 20:27 UTC, Cheukting commented
@webchick when you are ready, feel free to merge :-)

2024-02-13 04:29 UTC, webchick commented
Yay thanks!! 😄 @kdruckman requested a review as well, so I’ll hold to see what she has to say. (As well if there are any other comments.)

2024-02-15 18:21 UTC, kdruckman commented on CONTRIBUTING.md
> +* **Monthly Monthly DevRel Community meetings** which happen the second Thursday of the month at 16:30 UTC ([your timezone](https://time.is/1630_in_UTC)) for updates of general goings on and general
"Monthly" is repeated.

2024-02-15 18:30 UTC, kdruckman requested changes
This is fabulous @webchick! I only have a minor change and small suggestion.

2024-02-15 18:30 UTC, kdruckman commented on CONTRIBUTING.md
> +* **Monthly Monthly DevRel Community meetings** which happen the second Thursday of the month at 16:30 UTC ([your timezone](https://time.is/1630_in_UTC)) for updates of general goings on and general
"Monthly" is repeated.

2024-02-15 18:30 UTC, kdruckman commented on CONTRIBUTING.md
> +If you’d like feedback on your abstract or your talk, please join us during weekly office hours!
Should we link to the meeting calendar? (maybe also for the above meeting references too)
```suggestion
If you’d like feedback on your abstract or your talk, please join us during weekly office hours, which you can find on the [OpenSSF Community Calendar](https://openssf.org/getinvolved/)!
```

2024-02-16 02:03 UTC, webchick commented on CONTRIBUTING.md
> +* **Monthly Monthly DevRel Community meetings** which happen the second Thursday of the month at 16:30 UTC ([your timezone](https://time.is/1630_in_UTC)) for updates of general goings on and general
Well I COULD fix that but then are we sure people would know they’re monthly? I feel like maybe I should add another one for EMPHASIS!! 😂

Fixed, thank you!!

2024-02-16 02:05 UTC, webchick commented
Yay!! Thank you for the review! I believe now all review comments have been resolved, so back to you and will merge this once @kdruckman has signed off.

2024-02-20 16:45 UTC, kdruckman approved these changes
Looks good to merge!

2024-02-20 21:54 UTC, merged

2024-02-20 21:54 UTC, webchick commented
Woohoo! Thanks so much, all! 😄